# Site settings
title: "Jots"
description: "An ongoing collection of bits from inspiring pieces."
author: Andrea Buran
exclude: ['README.md']
version: '2018-12-29'

#baseurl: http://ranbureand.github.io/jots
baseurl: /

timezone: Europe/Rome
encoding: utf-8

future: true

collections:
  jots:
    output: true

# Build settings
markdown: kramdown

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..3

#Plugins
plugins: [jekyll-paginate]

# Pagination
paginate: 48
paginate_path: '/jots/page:num/'
